#
# starship.toml configuration file

[character]
success_symbol = '[>](bright-green bold)'
error_symbol = '[>](bright-red bold)'

[username]
style_root = 'red'
style_user = '#f7c635'
format = '[$user]($style)@'

[hostname]
ssh_only = false
style = 'fg:#FF6C1C'
format = '[$hostname]($style):'

[directory]
truncate_to_repo = false
style = 'fg:#09ECFF'
truncation_symbol = "…/"
#format = '[$path/]($style)[$read_only]($read_only_style) '

[status]
disabled = true
style = 'red'
map_symbol = true
symbol = '💥'
format = '[$symbol]($style)'

[ruby]
# don't trigger this module for environment variables
detect_variables = []
