#!/usr/bin/env bash
#
# update the config repository and get third party dependencies
if [ -z ${CONFIG_DIR+x} ]; then
    echo "Please set CONFIG_DIR to point to the directory of the config repo"
    exit 1
fi
if [ ! -d $CONFIG_DIR ]; then
    echo "Please set CONFIG_DIR to point to the directory of the config repo"
    exit 1
fi

# save the friendly path to bashrc
SHORTPATH=$(shortpath $CONFIG_DIR/bashrc)

# update our git repo
cd $CONFIG_DIR
echo
echo Pulling git repo:
git pull

echo
echo Pulling git submodules:
git submodule init
git submodule update --recursive

echo
echo Configuring bd:
rm -f bin/bd
ln -s submodules/bd/bd bin/bd
rm -f bash_completion.d/bd
ln -s submodules/bd/bash_completion.d/bd bash_completion.d/bd

echo
echo Retrieving iterm2 shell integration:
curl -L https://iterm2.com/misc/bash_startup.in \
-o lib/iterm2_shell_integration.bash

# macOS specific
if [[ $OSTYPE =~ darwin* ]]; then
    # TODO check if brew is installed, and if not, offer to do it
    echo
    echo Updating brew:
    brew update

    # install bash completion
    GOTIT=$( brew list | grep bash-completion@2 )
    if [ -z ${GOTIT+x} ]; then
        brew install bash-completion@2
    fi
    
    # install lesspipe
    GOTIT=$( brew list | grep lesspipe )
    if [ -z ${GOTIT+x} ]; then
        brew install lesspipe
    fi
    
fi

echo
echo Update complete. Type \""source $SHORTPATH"\" to update your current shell.
