#!/usr/bin/env bash
#
# update the config repository and get third party dependencies
if [ -z ${CONFIG_DIR+x} ]; then
    echo "Please set CONFIG_DIR to point to the directory of the config repo"
    exit 1
fi
if [ ! -d $CONFIG_DIR ]; then
    echo "Please set CONFIG_DIR to point to the directory of the config repo"
    exit 1
fi

# save the friendly path to bashrc
SHORTPATH=$(shortpath $CONFIG_DIR/bashrc)

# update our git repo
cd $CONFIG_DIR
echo
echo Pulling git repo:
git pull

echo
echo Pulling git submodules:
git submodule init
git submodule update --recursive

echo
echo Configuration bashmarks:
rm -f bashrc.d/bashmarks.bash
ln -s ../submodules/bashmarks/bashmarks.sh bashrc.d/bashmarks.bash

echo
echo Configuring bd:
rm -f bin/bd
ln -s ../submodules/bd/bd bin/bd
# remove bd because of a change we made on 7 Mar 2023
# at some point in the future the single line below can be removed
rm -f bash_completion.d/bd
rm -f bash_completion.d/bd.bash
ln -s ../submodules/bd/bash_completion.d/bd bash_completion.d/bd.bash

echo
echo Configuring commacd:
rm -f bashrc.d/commacd.sh
ln -s ../submodules/commacd/commacd.sh bashrc.d/commacd.sh

echo
echo Retrieving iterm2 shell integration:
curl -L https://iterm2.com/shell_integration/bash \
-o lib/iterm2_shell_integration.bash

# macOS specific
if [[ $OSTYPE =~ darwin* ]]; then
    # TODO check if brew is installed, and if not, offer to do it
    echo
    echo Updating brew:
    brew update

    # install bash completion
    GOTIT=$( brew list --formula | grep bash-completion@2 )
    if [ -z ${GOTIT+x} ]; then
        brew install bash-completion@2
    fi

    # install lesspipe
    GOTIT=$( brew list --formula | grep lesspipe )
    if [ -z ${GOTIT+x} ]; then
        brew install lesspipe
    fi

fi

echo
echo -n Installing dotfiles:
for FILE in $(ls -A dotfiles); do
    echo -n $FILE
    rm -f ~/$FILE
    ln -s $CONFIG_DIR/dotfiles/$FILE ~/$FILE
done
echo

echo
echo -n Installing .config directories:
for DIR in $(find dotconfig -type d -mindepth 1 -depth 1 -print | awk -F / '{ print $NF }'); do
    echo -n $DIR
#    rm -rf ~/.config/$DIR
#    ln -s $CONFIG_DIR/dotconfig/$DIR ~/.config/$DIR
done
echo

echo
echo Update complete. Type \""source $SHORTPATH"\" to update your current shell.
